import type { FruitFact, FruitType } from '../types/game';

export const FRUIT_TRIVIA: Record<FruitType, FruitFact> = {
  watermelon: {
    type: 'watermelon',
    name: 'Watermelon',
    emoji: '🍉',
    color: '#ff1744',
    vitamins: ['Vitamin C', 'Vitamin A', 'Lycopene', 'Hydration'],
    funFact: 'Watermelons are 92% water! They keep you super hydrated during sports and study sessions.',
    healthBenefit: 'High in Lycopene which protects your heart and muscles!',
  },
  banana: {
    type: 'banana',
    name: 'Banana',
    emoji: '🍌',
    color: '#ffd600',
    vitamins: ['Potassium', 'Vitamin B6', 'Fiber'],
    funFact: 'Bananas float in water because they are less dense than water!',
    healthBenefit: 'Potassium prevents muscle cramps and gives your brain steady energy.',
  },
  strawberry: {
    type: 'strawberry',
    name: 'Strawberry',
    emoji: '🍓',
    color: '#e53935',
    vitamins: ['Vitamin C', 'Manganese', 'Folate'],
    funFact: 'Strawberries are the only fruit with seeds on the outside! An average strawberry has 200 seeds.',
    healthBenefit: 'Packed with antioxidants that boost memory and immunity.',
  },
  pineapple: {
    type: 'pineapple',
    name: 'Pineapple',
    emoji: '🍍',
    color: '#ff8f00',
    vitamins: ['Bromelain', 'Vitamin C', 'Manganese'],
    funFact: 'It takes almost 2 to 3 years for a single pineapple to grow and mature on its plant!',
    healthBenefit: 'Contains Bromelain, an enzyme that aids digestion and reduces inflammation.',
  },
  orange: {
    type: 'orange',
    name: 'Orange',
    emoji: '🍊',
    color: '#ff6d00',
    vitamins: ['Vitamin C', 'Thiamine', 'Folate'],
    funFact: 'There are over 600 varieties of oranges worldwide!',
    healthBenefit: 'One orange provides 100% of your recommended daily Vitamin C intake to fight off colds.',
  },
  apple: {
    type: 'apple',
    name: 'Red Apple',
    emoji: '🍎',
    color: '#d32f2f',
    vitamins: ['Fiber', 'Vitamin C', 'Quercetin'],
    funFact: 'Apples float in water because 25% of their volume is actually air!',
    healthBenefit: 'High in pectin fiber which keeps your digestive system strong and healthy.',
  },
  dragonfruit: {
    type: 'dragonfruit',
    name: 'Dragonfruit',
    emoji: '🐉',
    color: '#e91e63',
    vitamins: ['Iron', 'Magnesium', 'Prebiotics'],
    funFact: 'Dragonfruit grows on a night-blooming cactus plant that only flowers in the dark!',
    healthBenefit: 'Rich in prebiotics that feed good gut bacteria for top digestion.',
  },
  kiwi: {
    type: 'kiwi',
    name: 'Kiwi',
    emoji: '🥝',
    color: '#76ff03',
    vitamins: ['Vitamin C', 'Vitamin K', 'Vitamin E'],
    funFact: 'Kiwifruit has more Vitamin C per gram than a fresh orange!',
    healthBenefit: 'Vitamin K helps your bones stay strong and aids blood clotting.',
  },
  coconut: {
    type: 'coconut',
    name: 'Coconut',
    emoji: '🥥',
    color: '#3e2723',
    vitamins: ['Electrolytes', 'Healthy Fats', 'Iron'],
    funFact: 'Coconut water was used as emergency IV plasma during World War II because it is sterile and isotonic!',
    healthBenefit: 'Natural electrolytes restore energy after exercising or playing hard.',
  },
  bomb: {
    type: 'bomb',
    name: 'Explosive Bomb',
    emoji: '💣',
    color: '#212121',
    vitamins: ['Danger!'],
    funFact: 'Dodge the bomb to maintain your slice combo!',
    healthBenefit: 'Stay sharp and fast to keep your score safe.',
  },
  junkfood: {
    type: 'junkfood',
    name: 'Unhealthy Junk Food',
    emoji: '🍔',
    color: '#bf360c',
    vitamins: ['Excess Sugar', 'Trans Fats'],
    funFact: 'Junk foods give quick sugar spikes followed by severe energy crashes!',
    healthBenefit: 'Avoid junk food bombs in game & real life to maintain peak energy.',
  },
};
